In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = a*2

np.vstack((a, b))

array([[1, 2, 3],
       [2, 4, 6]])

In [5]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 9]])


array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [27]:
ap = np.expand_dims(a, 1)
bp = ap*2
bp

combined = np.concatenate((ap, bp), axis=1)
combined

array([[1, 2],
       [2, 4],
       [3, 6]])

In [29]:
reshaped = np.reshape(combined, (1, 6))
reshaped

array([[1, 2, 2, 4, 3, 6]])

In [ ]:
def interleave(a, b, c):
    ''' Returns data set with a[0], b[0], c[0],
    a[1], b[1], c[1], etc.'''
    batch_size = a.shape[0]
    img_rows = a.shape[1]
    img_cols = a.shape[2]
    channels = a.shape[3]
    
    collected = [np.expand_dims(x, 1) for x in (a, b, c)]
    catted = np.concatenate(collected, axis=1)
    reshaped = np.reshape(catted, (1, 3*batch_size, img_rows, img_cols, channels))
    return reshaped

    

In [30]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [32]:
np.random.normal(size=3)

array([ 0.43232872, -0.0096141 ,  0.85474332])